CREATE TABLE `traffic_accidents` (
	`id` integer PRIMARY KEY NOT NULL,
	`record_number` text NOT NULL,
	`prefecture_code` integer NOT NULL,
	`police_station_code` text NOT NULL,
	`municipality_code` text,
	`lat` real NOT NULL,
	`lng` real NOT NULL,
	`occurred_at` text,
	`source_year` integer NOT NULL,
	`severity_code` integer,
	`accident_type_code` text,
	`accident_type_label` text,
	`fatalities` integer,
	`injuries` integer,
	`involves_child` integer DEFAULT false NOT NULL,
	`involves_pedestrian` integer DEFAULT false NOT NULL,
	`party_a_age` integer,
	`party_a_type_code` text,
	`party_a_type_label` text,
	`party_b_age` integer,
	`party_b_type_code` text,
	`party_b_type_label` text,
	`injury_level_a` text,
	`injury_level_b` text,
	`day_night_code` integer,
	`day_of_week` integer,
	`road_shape_code` text,
	`road_shape_label` text,
	`road_surface_code` integer,
	`road_surface_label` text,
	`road_width_code` text,
	`sidewalk_code` text,
	`sidewalk_label` text,
	`signal_code` text,
	`terrain_code` integer,
	`terrain_label` text,
	`weather_code` integer,
	`weather_label` text,
	`zone_regulation_code` text,
	`imported_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL
);
