/**
 * 標準シナリオ画像生成のフォールバックプロンプト。
 * generate-prompts API が失敗したときと、クライアント側でプロンプト未取得のときに使う。
 * サーバ専用の依存を持たないこと（クライアントコンポーネントからも import される）。
 *
 * 設計原則(緩和不可):
 * - 画像生成は「元写真の編集(edit)」として指示する(シーン再合成をさせない)。
 * - 写っているものだけラベル / 元写真のアスペクト比維持 / 顔・ナンバーの匿名化。
 * - CLOSED TEXT SET: 描いてよい文字列を完全列挙し、それ以外の文字を全面禁止する
 *   (英字透かし・日本語風の崩れ文字の混入を生成側で先回りして塞ぐ)。
 * - 'children' 等の児童言及を書かない(被害シーンとの組合せは画像モデルの安全フィルタを誘発し得る)。
 */

export const FALLBACK_VIZ_PROMPT = `Using the provided photo of a Japanese school route as the immutable base image, add a flat 2D hazard-annotation overlay layer on top. This is an image-editing task, not scene creation: do not redraw, repaint, move, remove, or re-synthesize anything in the underlying photograph; every area not covered by an overlay must remain identical to the input photo. Keep the photo's exact framing, full field of view, and original aspect ratio. If any human face is visible, repaint it as an unrecognizable soft blur covering the whole face; if any license plate is visible, repaint the entire plate as a blank surface with no characters. Mark up to four potential hazards, but ONLY those whose anchor object is actually visible in this photo — never invent an object to justify a label; if fewer apply, mark fewer: (1) fence or block-wall instability: semi-transparent red polygon (about 40% fill opacity, solid red outline) hugging the wall's silhouette + Japanese label "フェンス倒壊注意"; (2) utility pole failure risk: red outline hugging the pole + Japanese label "電柱倒壊注意"; (3) flooding-prone low spot or drainage: semi-transparent blue wash over the low road surface + Japanese label "冠水注意"; (4) fire spread exposure from adjacent dense or wooden buildings: semi-transparent amber tint over those buildings + Japanese label "延焼注意". Give each marked hazard a numbered circular badge (white numeral on the polygon's color) connected by a short leader line, and place each Japanese label on a high-contrast rounded pill directly beside its badge, on or immediately next to the anchor object it describes. Add a compact Japanese legend on a small opaque rounded panel at bottom-left listing only the colors actually used: "凡例 赤=倒壊・落下注意 / 青=冠水注意 / 橙=火災注意". CLOSED TEXT SET: the image may contain ONLY the Japanese labels listed above, that legend line, and marker numerals 1-4, each reproduced glyph-for-glyph in a clean bold Japanese gothic (sans-serif) typeface; no other characters of any script may appear anywhere — no deformed kanji-like glyphs, no alphabet, no captions, no watermark, no model names. The overlays must look like clean digital infographic graphics (flat vector style, sharp focus, balanced contrast, mobile-readable), not like physical signs or objects inside the scene. No graphic destruction, no gore.`

export const FALLBACK_SIMULATION_PROMPTS = {
  earthquake:
    "Edit the provided photo of a Japanese suburban street to show the same place moments after a moderate earthquake (Japan seismic intensity 5-upper). Keep the exact camera position, framing, lens, daylight, and the photo's original aspect ratio; keep every structure in its original position and modify only what this instruction describes. FIRST assess the actual visible condition of each structure in the photo, then apply damage strictly proportional to that condition: pristine or new surfaces get at most hairline cracks and a thin dust film; weathered surfaces get a few visible cracks running stair-step along mortar joints or radiating from corners, or a slight rigid lean at the base; only structures that already show cracks, rust or crumbling in the photo may lose a few blocks or small sections, fallen directly below their origin. Never bend poles mid-span and never crack pavement except along existing seams. Keep every undamaged structure identical so the street stays instantly recognizable. No people, no added vehicles; if any face or license plate is visible, repaint it unrecognizable (soft blur for faces, blank surface for plates). The scene reads as 'shaken but standing' in a calm, matter-of-fact documentary tone. Photorealistic, sharp focus, normal daylight. Do NOT show explosion-like destruction, dust clouds, collapsed buildings, darkened skies, or any horror-like mood. Do not add any text, lettering, numbers, or logos of any kind; keep real-world signage already present in the photo unchanged. No watermarks, no model names.",
  typhoon:
    "Edit the provided photo of a Japanese suburban street to show the same place right after typhoon-class wind (about 30 m/s). Keep the exact camera position, framing, lens, and the photo's original aspect ratio; keep every structure in its original position and modify only what this instruction describes. Choose ONE wind direction and keep every cue consistent with it: wet pavement with a dull sheen, leaves and small broken branches accumulated on the downwind side, lightweight objects (bins, cones, potted plants) toppled or shifted downwind, flexible signs and mesh fences bowed slightly downwind but still standing. Apply the mass rule: only objects a person could lift are displaced; solid structures stay intact — first check each structure's condition in the photo, and only a panel that already looks loose or rusted may be visibly bent. Sky overcast but normal daylight, no storm drama. Keep every unaffected structure identical. No people, no added vehicles; if any face or license plate is visible, repaint it unrecognizable (soft blur for faces, blank surface for plates). Calm, matter-of-fact documentary tone. Photorealistic, sharp focus. Do NOT show uprooted trees, destroyed buildings, debris flying in mid-air, darkened dramatic skies, or catastrophic damage. Do not add any text, lettering, numbers, or logos of any kind; keep real-world signage already present in the photo unchanged. No watermarks, no model names.",
  flood:
    "Edit the provided photo of a Japanese suburban street to show the same place during shallow urban flooding of 15-20 cm (ankle to shin depth). Keep the exact camera position, framing, lens, daylight, and the photo's original aspect ratio. Render ONE horizontally consistent waterline across the entire scene, calibrated to real anchors in the photo: a standard curb is about 15 cm high, so the water just reaches the curb top; wall bases and fence posts stand in the water. The water is silty brown and opaque enough to hide the road markings beneath it, with small ripples and matte, broken reflections of the poles and walls above; floating leaves and light debris; a damp high-water stain a few centimeters above the waterline on walls and curbs. Everything above the waterline stays exactly as in the photo. No people, no added vehicles; if any face or license plate is visible, repaint it unrecognizable (soft blur for faces, blank surface for plates). Calm, matter-of-fact documentary tone. Photorealistic, sharp focus. Do NOT show deep water, submerged cars, waves or torrents, falling rain streaks, or a dark stormy mood. Do not add any text, lettering, numbers, or logos of any kind; keep real-world signage already present in the photo unchanged. No watermarks, no model names.",
  fire:
    "Edit the provided photo of a Japanese suburban street to show subtle signs that a small fire is burning somewhere OUTSIDE the frame. Keep the exact camera position, framing, lens, layout, colors, and the photo's original aspect ratio. First choose the off-frame direction of the fire, then keep every cue consistent with it: a translucent smoke haze densest toward that edge of the frame and thinning across the scene, faint soot only on the surfaces facing that direction, and a slight warm tint confined to the haze itself — every surface keeps its normal daylight color, with no orange glow and no rim light, because no flames are visible anywhere. Distant objects are slightly softened by the haze while the foreground stays clear. Everything else stays exactly as in the photo. No people, no added vehicles; if any face or license plate is visible, repaint it unrecognizable (soft blur for faces, blank surface for plates). The image suggests 'a fire happened nearby' in a calm, matter-of-fact documentary tone — the street itself is not burning. Photorealistic, sharp focus. Do NOT show flames, burning or charred objects, thick black smoke filling the sky, or an apocalyptic mood. Do not add any text, lettering, numbers, or logos of any kind; keep real-world signage already present in the photo unchanged. No watermarks, no model names.",
} as const

export const FALLBACK_TABLE_MARKDOWN = [
  "| ハザード | 想定リスク (例) | その場でできる対策 (例) |",
  "|---|---|---|",
  "| 地震 | 塀のひび割れ・傾き / 落下物の可能性 / 路面の小さなひび | 塀から離れる / 迂回誘導 / 点検を依頼 |",
  "| 台風(強風) | 飛散物（植木鉢・看板）/ フェンス変形 / 枝の折損 | 緩んだ物を固定 / 安全側へ迂回案内 / 折れ枝を束ねて移動 |",
  "| 豪雨(冠水) | 道路冠水（15〜20cm）/ 排水詰まり / 滑りやすい路面 | 冠水エリアへの進入禁止 / 側溝のゴミ除去 / 足元注意喚起 |",
  "| 火災 | 煙による視界低下 / 近隣延焼リスク / 煤の付着 | 可燃物を遠ざける / 風上へ避難 / 小火は消火器で初期消火 |",
].join("\n")

/**
 * サーバ側で standard モードの生成プロンプト末尾に決定的に付与するガード。
 * 恒久ルール(アスペクト比維持・匿名化・余計な文字禁止)をLLM出力の版数に依存させないための最小文面。
 * 適用箇所は app/api/gemini/generate-image/route.ts のみ(generationMode === 'standard' の明示一致時のみ)。
 * 生成プロンプト側・フォールバック側には織り込まない(二重付与を設計上排除)。
 */
export const SCENE_PRESERVATION_GUARD_SUFFIX = `[Scene-preservation guard] The attached photo is the base image: preserve its exact framing and original aspect ratio, and leave every area you were not explicitly asked to change identical to the input photo. If any face or license plate is visible, repaint it unrecognizable (soft blur for faces, blank plate surface). Add no text beyond the Japanese labels and legend explicitly specified above (if none are specified, add no text at all); no watermarks, no model names.`
