import { index, integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core'

import { createdAt } from './common'

export const trafficAccidents = sqliteTable('traffic_accidents', {
  id: integer('id').primaryKey(),
  recordNumber: text('record_number').notNull(),
  prefectureCode: integer('prefecture_code').notNull(),
  policeStationCode: text('police_station_code').notNull(),
  municipalityCode: text('municipality_code'),
  latitude: real('lat').notNull(),
  longitude: real('lng').notNull(),
  occurredAt: text('occurred_at'),
  sourceYear: integer('source_year').notNull(),
  severityCode: integer('severity_code'),
  accidentTypeCode: text('accident_type_code'),
  accidentTypeLabel: text('accident_type_label'),
  fatalities: integer('fatalities'),
  injuries: integer('injuries'),
  involvesChild: integer('involves_child', { mode: 'boolean' }).notNull().default(false),
  involvesPedestrian: integer('involves_pedestrian', { mode: 'boolean' }).notNull().default(false),
  partyAAge: integer('party_a_age'),
  partyATypeCode: text('party_a_type_code'),
  partyATypeLabel: text('party_a_type_label'),
  partyBAge: integer('party_b_age'),
  partyBTypeCode: text('party_b_type_code'),
  partyBTypeLabel: text('party_b_type_label'),
  injuryLevelA: text('injury_level_a'),
  injuryLevelB: text('injury_level_b'),
  dayNightCode: integer('day_night_code'),
  dayOfWeek: integer('day_of_week'),
  roadShapeCode: text('road_shape_code'),
  roadShapeLabel: text('road_shape_label'),
  roadSurfaceCode: integer('road_surface_code'),
  roadSurfaceLabel: text('road_surface_label'),
  roadWidthCode: text('road_width_code'),
  sidewalkCode: text('sidewalk_code'),
  sidewalkLabel: text('sidewalk_label'),
  signalCode: text('signal_code'),
  terrainCode: integer('terrain_code'),
  terrainLabel: text('terrain_label'),
  weatherCode: integer('weather_code'),
  weatherLabel: text('weather_label'),
  zoneRegulationCode: text('zone_regulation_code'),
  importedAt: createdAt('imported_at'),
}, (table) => [
  index('idx_traffic_accidents_year_lat_lng').on(table.sourceYear, table.latitude, table.longitude),
  index('idx_traffic_accidents_child_year_lat_lng').on(table.involvesChild, table.sourceYear, table.latitude, table.longitude),
  index('idx_traffic_accidents_ped_year_lat_lng').on(table.involvesPedestrian, table.sourceYear, table.latitude, table.longitude),
])

/** 事故多発地点（scripts/migrate/build-traffic-hotspots.ts で事前計算。条件は lib/traffic-accident/hotspot-config.ts）。 */
export const accidentHotspots = sqliteTable('accident_hotspots', {
  id: integer('id').primaryKey(),
  datasetVersion: text('dataset_version').notNull(),
  latitude: real('lat').notNull(),
  longitude: real('lng').notNull(),
  radiusMeters: integer('radius_meters').notNull(),
  minYear: integer('min_year').notNull(),
  maxYear: integer('max_year').notNull(),
  accidentCount: integer('accident_count').notNull(),
  fatalCount: integer('fatal_count').notNull(),
  pedestrianCount: integer('pedestrian_count').notNull(),
  youngCount: integer('young_count').notNull(),
  byYearJson: text('by_year_json').notNull(),
  byClassJson: text('by_class_json').notNull(),
  peakHour: integer('peak_hour'),
  prefectureCode: integer('prefecture_code').notNull(),
  municipalityCode: text('municipality_code'),
  nationalRank: integer('national_rank').notNull(),
}, (table) => [
  index('idx_accident_hotspots_version_lat_lng').on(table.datasetVersion, table.latitude, table.longitude),
])
