// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/3d-route-poc" | "/admin/costs" | "/admin/dashboard" | "/admin/reports" | "/badges" | "/dashboard" | "/forgot-password" | "/hazard-game" | "/landing" | "/leaderboard" | "/login" | "/map" | "/missions" | "/mypage" | "/register" | "/report" | "/reset-password" | "/route-quiz" | "/routes" | "/safe-magazine" | "/safe-magazine/[slug]" | "/school-route-news" | "/school-route-news/[slug]" | "/tools/image-gen" | "/xroad"
type AppRouteHandlerRoutes = "/api/admin/costs" | "/api/admin/costs/budget" | "/api/admin/costs/mapbox-usage" | "/api/admin/reports" | "/api/cron/local-alert-fetcher" | "/api/cron/local-safety-alerts" | "/api/cron/push-danger-reports" | "/api/debug-env" | "/api/debug/mapbox" | "/api/gemini/generate-image" | "/api/gemini/generate-prompts" | "/api/hazard-game/analyze" | "/api/hazard/image" | "/api/hazard/route-risks" | "/api/image/process" | "/api/mapbox/directions" | "/api/mapbox/geocode" | "/api/mapbox/isochrone" | "/api/mapbox/matrix" | "/api/mapbox/tilequery" | "/api/push/notify-content" | "/api/push/notify-danger-report" | "/api/push/subscribe" | "/api/push/unsubscribe" | "/api/test-auth" | "/api/test-openai" | "/api/xroad" | "/api/xroad-proxy"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/3d-route-poc": {}
  "/admin": {}
  "/admin/costs": {}
  "/admin/dashboard": {}
  "/admin/reports": {}
  "/api/admin/costs": {}
  "/api/admin/costs/budget": {}
  "/api/admin/costs/mapbox-usage": {}
  "/api/admin/reports": {}
  "/api/cron/local-alert-fetcher": {}
  "/api/cron/local-safety-alerts": {}
  "/api/cron/push-danger-reports": {}
  "/api/debug-env": {}
  "/api/debug/mapbox": {}
  "/api/gemini/generate-image": {}
  "/api/gemini/generate-prompts": {}
  "/api/hazard-game/analyze": {}
  "/api/hazard/image": {}
  "/api/hazard/route-risks": {}
  "/api/image/process": {}
  "/api/mapbox/directions": {}
  "/api/mapbox/geocode": {}
  "/api/mapbox/isochrone": {}
  "/api/mapbox/matrix": {}
  "/api/mapbox/tilequery": {}
  "/api/push/notify-content": {}
  "/api/push/notify-danger-report": {}
  "/api/push/subscribe": {}
  "/api/push/unsubscribe": {}
  "/api/test-auth": {}
  "/api/test-openai": {}
  "/api/xroad": {}
  "/api/xroad-proxy": {}
  "/badges": {}
  "/dashboard": {}
  "/forgot-password": {}
  "/hazard-game": {}
  "/landing": {}
  "/leaderboard": {}
  "/login": {}
  "/map": {}
  "/missions": {}
  "/mypage": {}
  "/register": {}
  "/report": {}
  "/reset-password": {}
  "/route-quiz": {}
  "/routes": {}
  "/safe-magazine": {}
  "/safe-magazine/[slug]": { "slug": string; }
  "/school-route-news": {}
  "/school-route-news/[slug]": { "slug": string; }
  "/tools/image-gen": {}
  "/xroad": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
