// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/3d-route-poc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/3d-route-poc">> = Specific
  const handler = {} as typeof import("../../../app/3d-route-poc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/costs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/costs">> = Specific
  const handler = {} as typeof import("../../../app/admin/costs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/badges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/badges">> = Specific
  const handler = {} as typeof import("../../../app/badges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hazard-game/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hazard-game">> = Specific
  const handler = {} as typeof import("../../../app/hazard-game/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../../app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../../app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/map">> = Specific
  const handler = {} as typeof import("../../../app/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/missions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/missions">> = Specific
  const handler = {} as typeof import("../../../app/missions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mypage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage">> = Specific
  const handler = {} as typeof import("../../../app/mypage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../../app/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/route-quiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/route-quiz">> = Specific
  const handler = {} as typeof import("../../../app/route-quiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/routes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/routes">> = Specific
  const handler = {} as typeof import("../../../app/routes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/safe-magazine/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safe-magazine/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/safe-magazine/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/safe-magazine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safe-magazine">> = Specific
  const handler = {} as typeof import("../../../app/safe-magazine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/school-route-news/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school-route-news/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/school-route-news/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/school-route-news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school-route-news">> = Specific
  const handler = {} as typeof import("../../../app/school-route-news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tools/image-gen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/image-gen">> = Specific
  const handler = {} as typeof import("../../../app/tools/image-gen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/xroad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/xroad">> = Specific
  const handler = {} as typeof import("../../../app/xroad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/costs/budget/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/costs/budget">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/costs/budget/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/costs/mapbox-usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/costs/mapbox-usage">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/costs/mapbox-usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/costs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/costs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/costs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/local-alert-fetcher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/local-alert-fetcher">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/local-alert-fetcher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/local-safety-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/local-safety-alerts">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/local-safety-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/push-danger-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/push-danger-reports">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/push-danger-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug-env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-env">> = Specific
  const handler = {} as typeof import("../../../app/api/debug-env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug/mapbox/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/mapbox">> = Specific
  const handler = {} as typeof import("../../../app/api/debug/mapbox/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/gemini/generate-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gemini/generate-image">> = Specific
  const handler = {} as typeof import("../../../app/api/gemini/generate-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/gemini/generate-prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gemini/generate-prompts">> = Specific
  const handler = {} as typeof import("../../../app/api/gemini/generate-prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/hazard-game/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hazard-game/analyze">> = Specific
  const handler = {} as typeof import("../../../app/api/hazard-game/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/hazard/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hazard/image">> = Specific
  const handler = {} as typeof import("../../../app/api/hazard/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/hazard/route-risks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hazard/route-risks">> = Specific
  const handler = {} as typeof import("../../../app/api/hazard/route-risks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/image/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/image/process">> = Specific
  const handler = {} as typeof import("../../../app/api/image/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mapbox/directions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mapbox/directions">> = Specific
  const handler = {} as typeof import("../../../app/api/mapbox/directions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mapbox/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mapbox/geocode">> = Specific
  const handler = {} as typeof import("../../../app/api/mapbox/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mapbox/isochrone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mapbox/isochrone">> = Specific
  const handler = {} as typeof import("../../../app/api/mapbox/isochrone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mapbox/matrix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mapbox/matrix">> = Specific
  const handler = {} as typeof import("../../../app/api/mapbox/matrix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mapbox/tilequery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mapbox/tilequery">> = Specific
  const handler = {} as typeof import("../../../app/api/mapbox/tilequery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/push/notify-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/notify-content">> = Specific
  const handler = {} as typeof import("../../../app/api/push/notify-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/push/notify-danger-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/notify-danger-report">> = Specific
  const handler = {} as typeof import("../../../app/api/push/notify-danger-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/push/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/subscribe">> = Specific
  const handler = {} as typeof import("../../../app/api/push/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/push/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/unsubscribe">> = Specific
  const handler = {} as typeof import("../../../app/api/push/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test-auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-auth">> = Specific
  const handler = {} as typeof import("../../../app/api/test-auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test-openai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-openai">> = Specific
  const handler = {} as typeof import("../../../app/api/test-openai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/xroad-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/xroad-proxy">> = Specific
  const handler = {} as typeof import("../../../app/api/xroad-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/xroad/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/xroad">> = Specific
  const handler = {} as typeof import("../../../app/api/xroad/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
